### PR TITLE
feat: set virtual scroll rows to be fixed height

### LINKED ISSUE #67: virtual scroll with variable sized items is broken
This is especially noticeable when adding a multiline notes column. I've tried to use the `AutoSizeVirtualScrollStrategy` from '@angular/cdk-experimental/scrolling', but couldn't get it to work.

### PR DESCRIPTION
**Pull request by steve-haar**
fixes #67

### CODE REVIEW

File: grid-demo/src/app/angular/row-dom-performance/custom-clr-virtual-rows.directive.ts [hunk 1]
```diff
@@ -40,7 +40,7 @@ type CdkVirtualForInputs<T> = Partial<Pick<CdkVirtualForOf<T>, CdkVirtualForInpu
 type CdkFixedSizeVirtualScrollInputs = Pick<CdkFixedSizeVirtualScroll, 'itemSize' | 'minBufferPx' | 'maxBufferPx'>;
 
 const defaultCdkFixedSizeVirtualScrollInputs: CdkFixedSizeVirtualScrollInputs = {
-  itemSize: 36,
+  itemSize: 72,
```
Comment (kevinbuhmann) [inline grid-demo/src/app/angular/row-dom-performance/custom-clr-virtual-rows.directive.ts:43]: I think the default should still be 36.

**Review by kevinbuhmann — APPROVED** [review]

File: grid-demo/src/app/angular/final-demo/final-demo.component.scss [hunk 2]
```diff
@@ -2,6 +2,17 @@ clr-datagrid {
   height: 500px;
 }
 
+clr-dg-row {
+  height: 72px;
+}
```
Comment (kevinbuhmann) [inline grid-demo/src/app/angular/final-demo/final-demo.component.scss:7]: The active cell border isn't the correct size. I think it would be better to remove this and set `height: 50px;` (72px - 11px vertical padding) in the `.cell-wrapper` rule.

**Review by kevinbuhmann — CHANGES_REQUESTED** [review]

File: grid-demo/src/app/angular/final-demo/final-demo.component.scss (hunk 2 above)
Comment (kevinbuhmann) [reply grid-demo/src/app/angular/final-demo/final-demo.component.scss:7]: I already have this change locally from testing. I can push it and approve if you want.

Comment (steve-haar) [reply grid-demo/src/app/angular/final-demo/final-demo.component.scss:7]: yes, please do

Comment (steve-haar) [reply grid-demo/src/app/angular/final-demo/final-demo.component.scss:7]: yes, please do. I may have to adjust the line-clamping number

Comment (kevinbuhmann) [reply grid-demo/src/app/angular/final-demo/final-demo.component.scss]: Okay, pushed.

**Review by kevinbuhmann — APPROVED** [review]
